name: Build and Push
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn package

      - name: Build Docker Image
        run: |
          docker build -t padajno/user-service:latest .
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push padajno/user-service:latest